from stanfordkarel import *


def main():
    """ Karel code goes here! """
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    beepers_in_bag()
    turn_left()
    move()
    move()
    move()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    move()
    put_beeper()
    move()
    move()
    put_beeper()
    move()
    move()
    put_beeper()
    turn_left()
    turn_left()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    move()
    put_beeper()
    move()
    move()
    put_beeper()
    turn_left()
    move()
    turn_left()
    move()
    put_beeper()
    move()
    move()
    put_beeper()
    turn_left()
    turn_left()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    turn_left()
    turn_left()
    turn_left()
    move()
    move()
    move()
    move()
    turn_left()
    turn_left()
    pass


if __name__ == "__main__":
    run_karel_program()